<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Innkeep2.Models\Innkeep2.Models.csproj" />
      <ProjectReference Include="..\Innkeep2.Requests\Innkeep2.Requests.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Interfaces\" />
    </ItemGroup>

</Project>
