// <auto-generated />
using System;
using Innkeep2.Cloud.AppDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innkeep2.Cloud.AppDb.Migrations
{
    [DbContext(typeof(InnkeepCloudDbContext))]
    [Migration("20260917095432_Added Api Keys")]
    partial class AddedApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Innkeep2.Cloud.AppDb.Models.InnkeepCloudSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PretixEventSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PretixOrganizerSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOrderDatabasePath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedTssId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseTestMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("InnkeepCloudSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
