// <auto-generated />
using Innkeep2.Cloud.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Innkeep2.Cloud.Database.Migrations
{
    [DbContext(typeof(InnkeepCloudDbContext))]
    [Migration("20260808100427_Settings Setup")]
    partial class SettingsSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Innkeep2.Cloud.Database.Models.InnkeepCloudSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PretixEventSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PretixOrganizerSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InnkeepCloudSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
